version: '3.7'

services:
  bps-sign-in-out:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CREDENTIALS_PATH=${GOOGLE_CREDENTIALS_PATH}
    volumes:
      - ${LOCAL_GOOGLE_CREDENTIALS_PATH}:${GOOGLE_CREDENTIALS_PATH}
      - ./grades.csv:/app/grades.csv  # Mount the CSV file inside the container

